version: "3"
services:
  postgres:
    restart: always
    image: eutechnic/postgresql:10.3
    ports:
      - "5432:5432"
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=eutechnic
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql
